services:
  - type: web
    name: car-management-api
    env: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: CORS_ORIGINS
        value: https://fullstack-lab-work.vercel.app

databases:
  - name: cardb
    databaseName: cardb
    user: admin

